pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/shreyakhangan/devops-fullstack-app.git'  // Replace with your repo URL
        ECR_REGISTRY = '961341543402.dkr.ecr.us-east-1.amazonaws.com'
        IMAGE_NAME = 'techverito/frontend'
        DOCKER_CREDENTIALS_ID = 'ecr' // Jenkins credentials ID for ECR
        AWS_REGION = 'us-east-1'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('frontend') {
                    sh "docker build -t ${ECR_REGISTRY}/${IMAGE_NAME} ."
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: "${DOCKER_CREDENTIALS_ID}"]]) {
                        // Authenticate to ECR and push the Docker image
                        sh """
                            aws ecrrr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REGISTRY}
                            docker push ${ECR_REGISTRY}/${IMAGE_NAME}
                        """
                    }
                }
            }
        }
    }
}

