pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.dev/shreyakhangan/devops-fullstack-app'  // Replace with your repo URL
        DOCKER_CREDENTIALS_ID = 'ecr' // Jenkins credentials ID for ECR
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t 961341543402.dkr.ecr.us-east-1.amazonaws.com/techverito .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    // Authenticate and push the image to ECR
                    sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 095214138254.dkr.ecr.us-east-1.amazonaws.com'
                    sh 'docker push 961341543402.dkr.ecr.us-east-1.amazonaws.com/techverito'
                }
            }
        }
    }
}